services:
  api:
    image: finnance-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:postgresql://db"
      DB_USER: postgres
      DB_PASSWORD: 85843449
      JWT_SECRET: lkejdgyif68f3vkagv7v@wsbc7syijvf*g3m908gcwvieeast5k6r@Ry4h
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 85843449
      POSTGRES_USER: postgres
      POSTGRES_BD: finnance